### ISSUE TITLE
Ensure Installed for Packages Other Than Lsps

### ISSUE THREAD

**Issue by mesa123123** [williamboman/mason-lspconfig.nvim#83]
### Is your feature request related to a problem? Please describe.

Just downloaded the latest update and suddenly this error appeared:
![image](https://user-images.githubusercontent.com/22901019/196314492-9a8fc362-11db-4eb1-b8a3-1445abec9d25.png)
I feel like since we can install things such as debugpy in mason we should be able to ensure its installation.

### Describe the solution you'd like

A way to ensure the installation of all packages mason provides for install not just the ones that can be loaded to lsp config
(note i've aliased installed to require('mason-lspconfig')
![image](https://user-images.githubusercontent.com/22901019/196314680-f584b4c2-1f19-4ba4-886b-e38cab182956.png)
Is currently what works without error but there are packages I don't load through the lsp but through things like Null-ls.nvim in order to improve my development experience, perhaps something like:
``` lua
require('mason.lspconfig').setup({ automatic_installation = true,
ensure_installed =  { lsp = { 'bashls' }, dap = {'bash-debug-adapter'}, linter = { shellcheck }, formatter = {'shellharden'} }
```
It would really help out a bunch because I love mason for being a great package manager for all of my lsp needs in extending the capabilities of nvim!

### Describe potential alternatives you've considered

I'm not sure? Maybe something that integrates null-ls valid types into mason-lsp? Though there is nothing on it in the null-ls.nvim repository to my knowledge

**Comment by mesa123123** [comment]
Sorry if this is actually meant for mason.nvim repo instead? Maybe theres a way to add the enhancement there?
It might be a better use case for mason.nvim?

**Comment by williamboman** [comment]
Hey! So the warning message was introduced to give people a heads up that they're providing invalid values that have no effect. The `ensure_installed` feature itself was ported from nvim-lsp-installer to mason-lspconfig in order to ensure feature parity and remove any switching costs related to migrating to Mason. This is why this feature only exists in mason-lspconfig for now.

As for automatic/programmatic installation of all kinds of packages, see https://github.com/williamboman/mason.nvim/issues/103. You can also use https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim as a complement for exactly this feature. You can also [code it up yourself](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md), which will not require many lines of code and gives you full control in terms of the how and when it should run installations & updates.

**Comment by mesa123123** [comment]
Cheers for this! I was a bit lost in the documentation and realized that coding on up myself would not be a hard ask! I'll definitely get onto having a look at the tools installer too!

Cheers!

P.S. I'm loving having a full package manager for the various third party stuff!
